// Story data for Pratik's Journey - A narrative RPG portfolio
// Each chapter represents a real career milestone

export const chapters = [
    {
        id: 'iist',
        number: 1,
        title: 'The Launchpad',
        subtitle: 'IIST, Trivandrum (2015-2019)',
        setting: 'Indian Institute of Space Science and Technology',
        emoji: '🚀',
        color: '#3b82f6',
        scenes: [
            {
                id: 'intro',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "2015. You've just received something extraordinary...",
            },
            {
                id: 'scholarship',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "A Government of India scholarship worth ₹3.86 Lakh. One of the few selected for India's elite space science institute.",
            },
            {
                id: 'campus',
                type: 'dialogue',
                speaker: 'PRATIK',
                text: "I walked into IIST thinking I'd become a scientist. Everyone here was brilliant. The path was clear: rockets, satellites, ISRO.",
            },
            {
                id: 'doubt',
                type: 'dialogue',
                speaker: 'PRATIK',
                text: "But something felt... off. I loved understanding systems, but I wanted to build things people actually used. Not just equations on paper.",
            },
            {
                id: 'professor',
                type: 'dialogue',
                speaker: 'PROFESSOR',
                text: "Pratik, your technical skills are strong. But I notice you spend more time questioning 'why' than 'how'. That's unusual here.",
            },
            {
                id: 'decision1',
                type: 'decision',
                prompt: "You're at a crossroads. Most IIST grads join ISRO. But you're drawn to something different. What do you do?",
                choices: [
                    {
                        id: 'traditional',
                        text: 'Follow the ISRO path - it\'s safe and prestigious',
                        outcome: 'safe',
                    },
                    {
                        id: 'explore',
                        text: 'Explore business and product - where systems meet people',
                        outcome: 'correct',
                    },
                    {
                        id: 'confused',
                        text: 'Stay confused and see what happens',
                        outcome: 'confused',
                    },
                ],
            },
            {
                id: 'outcome_correct',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "You chose to explore. While others prepared for ISRO, you started reading about startups, product management, and how technology creates value.",
                condition: { decision: 'decision1', choice: 'explore' },
            },
            {
                id: 'outcome_wrong',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "That's not what Pratik chose. He decided to explore business and product - where systems meet people. The unconventional path.",
                condition: { decision: 'decision1', choice: '!explore' },
            },
            {
                id: 'graduation',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "2019. B.Tech complete. Instead of joining ISRO, you're heading home to Nagpur. To a manufacturing plant. Everyone thinks you're crazy.",
            },
        ],
        badge: {
            name: 'Launchpad Badge',
            emoji: '🚀',
            skill: 'Questioning conventional paths',
        },
    },
    {
        id: 'polaris',
        number: 2,
        title: 'The Factory Floor',
        subtitle: 'Polaris Manufacturing, Nagpur (2019-2020)',
        setting: 'Manufacturing plant, 5:30 AM',
        emoji: '🏭',
        color: '#f59e0b',
        scenes: [
            {
                id: 'intro',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "Your first job: Founding Chief of Operations at a $2M manufacturing company. Not glamorous. But formative.",
            },
            {
                id: 'factory',
                type: 'dialogue',
                speaker: 'PRATIK',
                text: "5:30 AM. I walked the factory floor every morning. Watched the machines. Talked to the workers. Something wasn't right.",
            },
            {
                id: 'worker',
                type: 'dialogue',
                speaker: 'WORKER',
                text: "Sir, we're just standing here half the day. Waiting for materials. Waiting for the previous batch. Always waiting.",
            },
            {
                id: 'observation',
                type: 'dialogue',
                speaker: 'PRATIK',
                text: "I started timing everything. The idle time was insane. Workers were productive, but the system was broken.",
            },
            {
                id: 'decision1',
                type: 'decision',
                prompt: "The production line keeps stopping. Workers are idle 40% of the time. What do you do?",
                choices: [
                    {
                        id: 'accept',
                        text: 'Accept it - manufacturing is just like this',
                        outcome: 'wrong',
                    },
                    {
                        id: 'blame',
                        text: 'Blame the workers - they must be slacking',
                        outcome: 'wrong',
                    },
                    {
                        id: 'investigate',
                        text: 'Investigate the root cause - map the entire flow',
                        outcome: 'correct',
                    },
                ],
            },
            {
                id: 'outcome_correct',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "You mapped every step. Found the bottlenecks. Deployed real-time tracking. The data revealed everything.",
                condition: { decision: 'decision1', choice: 'investigate' },
            },
            {
                id: 'outcome_wrong',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "That's not what Pratik did. He investigated the root cause - mapped the entire production flow. The data revealed everything.",
                condition: { decision: 'decision1', choice: '!investigate' },
            },
            {
                id: 'solution',
                type: 'dialogue',
                speaker: 'PRATIK',
                text: "We built a simple tracking system. Real-time visibility into every bottleneck. Workers knew exactly when materials were coming.",
            },
            {
                id: 'result',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "Result: 73% reduction in production idle time. Your first taste of operational excellence. But you wanted more.",
            },
            {
                id: 'mba',
                type: 'dialogue',
                speaker: 'PRATIK',
                text: "I needed frameworks. Structure. I applied to IIM Calcutta - India's toughest business school. And somehow, got in.",
            },
        ],
        badge: {
            name: 'Operations Badge',
            emoji: '🏭',
            skill: 'Ground-level problem solving',
        },
    },
    {
        id: 'iim',
        number: 3,
        title: 'The Crucible',
        subtitle: 'IIM Calcutta (2020-2022)',
        setting: 'Joka campus, late night',
        emoji: '🎓',
        color: '#8b5cf6',
        scenes: [
            {
                id: 'intro',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "IIM Calcutta. India's oldest and one of its toughest business schools. 450+ of the smartest minds in the country.",
            },
            {
                id: 'campus',
                type: 'dialogue',
                speaker: 'PRATIK',
                text: "The first semester broke everyone. Case studies until 3 AM. Presentations at 8 AM. Sleep was optional.",
            },
            {
                id: 'competition',
                type: 'dialogue',
                speaker: 'TEAMMATE',
                text: "Pratik! Amazon ACE case competition. 48 hours. We need to crack this.",
            },
            {
                id: 'case',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "The problem: Design a new marketplace vertical for Amazon India. Ambiguous. Complex. Just like real PM work.",
            },
            {
                id: 'decision1',
                type: 'decision',
                prompt: "You have 48 hours to crack this case. 200+ teams competing. How do you start?",
                choices: [
                    {
                        id: 'solutions',
                        text: 'Jump straight into solutions - time is short',
                        outcome: 'wrong',
                    },
                    {
                        id: 'problem',
                        text: 'Spend the first 6 hours defining the problem clearly',
                        outcome: 'correct',
                    },
                    {
                        id: 'research',
                        text: 'Research every competitor extensively',
                        outcome: 'partial',
                    },
                ],
            },
            {
                id: 'outcome_correct',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "Your team spent hours just understanding the problem. What does Amazon really need? What's the user pain? This clarity won you the case.",
                condition: { decision: 'decision1', choice: 'problem' },
            },
            {
                id: 'outcome_wrong',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "Pratik's team spent the first 6 hours just defining the problem. No solutions yet. Just clarity. That discipline won them the case.",
                condition: { decision: 'decision1', choice: '!problem' },
            },
            {
                id: 'results',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "Amazon ACE Finalist. Flipkart Wired 5.0 Finalist. Ranked 52 out of 450+. Top 12% of the class.",
            },
            {
                id: 'placement',
                type: 'dialogue',
                speaker: 'PRATIK',
                text: "Placement season. I had one focus: Product Management. I wanted to build, not just advise. Times Internet made the offer.",
            },
        ],
        badge: {
            name: 'Strategy Badge',
            emoji: '🎓',
            skill: 'Structured thinking under pressure',
        },
    },
    {
        id: 'times',
        number: 4,
        title: 'The Media Machine',
        subtitle: 'Times Internet (2022-2024)',
        setting: 'Times of India HQ, Noida',
        emoji: '📺',
        color: '#ef4444',
        scenes: [
            {
                id: 'intro',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "Times Internet. India's largest digital media company. 500+ million monthly users. Your first real PM role.",
            },
            {
                id: 'desk',
                type: 'dialogue',
                speaker: 'PRATIK',
                text: "Day one. I'm responsible for AdTech - the revenue engine. Daily standups. Sprint planning. Real stakes.",
            },
            {
                id: 'challenge1',
                type: 'dialogue',
                speaker: 'VP_REVENUE',
                text: "Pratik, we need $500K more in ad revenue. Our inventory isn't optimized. Build something.",
            },
            {
                id: 'problem1',
                type: 'dialogue',
                speaker: 'PRATIK',
                text: "I dug into the data. Premium ad slots were being sold at discount rates. Low-value ads were blocking high-value ones. The allocation was dumb.",
            },
            {
                id: 'decision1',
                type: 'decision',
                prompt: "Ad inventory is being wasted. Premium slots sold cheap. How do you fix it?",
                choices: [
                    {
                        id: 'prices',
                        text: 'Just raise prices across the board',
                        outcome: 'wrong',
                    },
                    {
                        id: 'sales',
                        text: 'Hire more salespeople to sell better',
                        outcome: 'wrong',
                    },
                    {
                        id: 'engine',
                        text: 'Build a real-time allocation engine with smart pricing logic',
                        outcome: 'correct',
                    },
                ],
            },
            {
                id: 'orchestrator',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "You built the 'Ad Orchestrator' - a real-time inventory allocation system. It dynamically priced and assigned ads based on user context.",
                condition: { decision: 'decision1', choice: 'engine' },
            },
            {
                id: 'orchestrator_alt',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "Pratik built the 'Ad Orchestrator' - a real-time allocation engine with smart pricing. Not just raising prices, but optimizing every impression.",
                condition: { decision: 'decision1', choice: '!engine' },
            },
            {
                id: 'result1',
                type: 'dialogue',
                speaker: 'VP_REVENUE',
                text: "$500K+ in annualized revenue. From one product. That's the kind of impact we need.",
            },
            {
                id: 'uschallenge',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "Then came the US launch. Times of India expanding to America. Different regulations. Different users. Massive technical challenge.",
            },
            {
                id: 'worldcup',
                type: 'dialogue',
                speaker: 'PRATIK',
                text: "And then... Cricket World Cup. 10x traffic spike. A/B testing every headline. Every thumbnail. Every placement.",
            },
            {
                id: 'result2',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "Result: 2x pageviews. 18% CTR uplift. 75% faster deployments after CMS migration. But something was pulling you elsewhere...",
            },
            {
                id: 'transition',
                type: 'dialogue',
                speaker: 'PRATIK',
                text: "Media was exciting. But I wanted to build 0→1. Not optimize existing products. I wanted to create something from nothing.",
            },
        ],
        badge: {
            name: 'Revenue Badge',
            emoji: '📺',
            skill: 'Scaling products with business impact',
        },
    },
    {
        id: 'ziki',
        number: 5,
        title: 'The Marketplace',
        subtitle: 'Ziki, Mumbai (2024-Present)',
        setting: 'Startup office, Mumbai',
        emoji: '🛒',
        color: '#10b981',
        scenes: [
            {
                id: 'intro',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "2024. You join Ziki - a hyperlocal services marketplace. The challenge: Build something from nothing. True 0→1.",
            },
            {
                id: 'start',
                type: 'dialogue',
                speaker: 'PRATIK',
                text: "Week one. I'm managing a team of 15. Tech + Design. The product exists, but it's struggling. Utilities marketplace. Plumbers, electricians.",
            },
            {
                id: 'problem',
                type: 'dialogue',
                speaker: 'CEO',
                text: "Pratik, the margins on utilities are killing us. We make 5% on each booking. Not sustainable.",
            },
            {
                id: 'research',
                type: 'dialogue',
                speaker: 'PRATIK',
                text: "I went to the ground. 50+ interviews. Focus groups. Talked to users directly. The insight hit me like a truck.",
            },
            {
                id: 'insight',
                type: 'dialogue',
                speaker: 'USER',
                text: "I don't just need a plumber. I want experiences. Will you help me plan my kid's birthday party? Find a personal trainer? Plan a trip?",
            },
            {
                id: 'decision1',
                type: 'decision',
                prompt: "The marketplace is struggling. Low margins on utilities. Users are asking for experiences. What do you do?",
                choices: [
                    {
                        id: 'utilities',
                        text: 'Double down on utilities - raise prices',
                        outcome: 'wrong',
                    },
                    {
                        id: 'both',
                        text: 'Do both utilities and experiences - spread thin',
                        outcome: 'partial',
                    },
                    {
                        id: 'pivot',
                        text: 'Pivot to high-margin experiential services',
                        outcome: 'correct',
                    },
                ],
            },
            {
                id: 'pivot',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "You led the pivot. Killed low-margin utilities. Launched 4 new experience categories: Travel, Finance, Fitness, Skilling, Celebrations.",
                condition: { decision: 'decision1', choice: 'pivot' },
            },
            {
                id: 'pivot_alt',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "Pratik made the bold call. He pivoted Ziki from low-margin utilities to high-margin experiential services. A complete strategic reorientation.",
                condition: { decision: 'decision1', choice: '!pivot' },
            },
            {
                id: 'execution',
                type: 'dialogue',
                speaker: 'PRATIK',
                text: "Then came execution. 100+ vendor onboarding. Automated verification. Fulfilment tracking. AI voice agent for complaints. Promo engine.",
            },
            {
                id: 'decision2',
                type: 'decision',
                prompt: "Vendors are slow to onboard. 2 weeks per vendor. How do you scale?",
                choices: [
                    {
                        id: 'hire',
                        text: 'Hire more operations people',
                        outcome: 'wrong',
                    },
                    {
                        id: 'lower',
                        text: 'Lower quality standards to speed up',
                        outcome: 'wrong',
                    },
                    {
                        id: 'automate',
                        text: 'Automate verification + onboarding',
                        outcome: 'correct',
                    },
                ],
            },
            {
                id: 'automation',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "You automated everything. Vendor verification. Document checks. Onboarding flows. Cut activation time by 70%.",
                condition: { decision: 'decision2', choice: 'automate' },
            },
            {
                id: 'automation_alt',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "Pratik automated the onboarding process end-to-end. Not more people. Smarter systems. 70% faster activation.",
                condition: { decision: 'decision2', choice: '!automate' },
            },
            {
                id: 'results',
                type: 'dialogue',
                speaker: 'NARRATOR',
                text: "The results: +13% MoM GMV. 100+ verified partners. CSAT +20%. 75% on-time delivery. The marketplace was finally working.",
            },
            {
                id: 'reflection',
                type: 'dialogue',
                speaker: 'PRATIK',
                text: "This is what I love. Taking something broken, understanding the real problem, and building systems that actually work.",
            },
        ],
        badge: {
            name: 'Marketplace Badge',
            emoji: '🛒',
            skill: '0→1 building & strategic pivots',
        },
    },
];

export const sideQuests = {
    id: 'projects',
    title: 'Side Quests',
    subtitle: 'Personal Projects',
    emoji: '🧪',
    scenes: [
        {
            id: 'intro',
            type: 'dialogue',
            speaker: 'NARRATOR',
            text: "The best PMs build on their own time. Here's what Pratik shipped after hours.",
        },
        {
            id: 'chefsync_intro',
            type: 'dialogue',
            speaker: 'PRATIK',
            text: "ChefSync started as a weekend experiment. An AI cooking assistant. Simple chat interface. 'Tell me what you have, I'll suggest recipes.'",
        },
        {
            id: 'chefsync_problem',
            type: 'dialogue',
            speaker: 'PRATIK',
            text: "Users tried it once and never came back. The product worked. The AI was smart. But nobody wanted to use it.",
        },
        {
            id: 'chefsync_insight',
            type: 'dialogue',
            speaker: 'PRATIK',
            text: "I forced myself to use it while cooking. Dirty hands. Hungry. Having to type. That's when I realized: the chat interface was wrong.",
        },
        {
            id: 'chefsync_solution',
            type: 'dialogue',
            speaker: 'NARRATOR',
            text: "He killed the chat. Built a Tinder-style swipe deck. Swipe right to save, left to skip. No typing. Result: +325% retention.",
        },
        {
            id: 'speakeasy_intro',
            type: 'dialogue',
            speaker: 'PRATIK',
            text: "SpeakEasy came from personal frustration. I've tried learning Spanish for years. Every app made me more anxious, not less.",
        },
        {
            id: 'speakeasy_insight',
            type: 'dialogue',
            speaker: 'PRATIK',
            text: "Every app interrupts you. Shows red 'INCORRECT' text. You lose hearts. Your brain associates speaking with failure.",
        },
        {
            id: 'speakeasy_solution',
            type: 'dialogue',
            speaker: 'NARRATOR',
            text: "He built a 'judgement-free' AI. Never interrupts. Always acknowledges effort first. Sandwiches corrections between praise. Result: 65% D1 retention.",
        },
        {
            id: 'lesson',
            type: 'dialogue',
            speaker: 'PRATIK',
            text: "Both taught me the same thing: Don't wrap technology in a UI. Solve the actual human problem.",
        },
    ],
    badge: {
        name: 'Builder Badge',
        emoji: '🧪',
        skill: 'Full-stack product execution',
    },
};

export const epilogue = [
    {
        id: 'ending',
        type: 'dialogue',
        speaker: 'NARRATOR',
        text: "And that's the journey so far. From space science to startups. From factory floors to marketplaces.",
    },
    {
        id: 'philosophy',
        type: 'dialogue',
        speaker: 'PRATIK',
        text: "I build systems that solve specific human problems. No fluff. Just mechanics, incentives, and outcomes.",
    },
    {
        id: 'cta',
        type: 'dialogue',
        speaker: 'NARRATOR',
        text: "Ready to dig deeper? Explore the full case studies. Or let's talk.",
    },
];
